repos:
  # Code formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        name: Check yaml files
      - id: end-of-file-fixer
        name: Fix EOF
      - id: trailing-whitespace
        name: Remove trailing whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black

  # Quality analysis
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
